/** Códigos de negocio del panel → HTTP. Compartido por las rutas de la API. */
export const ADMIN_RESERVATION_HTTP_STATUS: Record<string, number> = {
  RESERVATION_NOT_FOUND: 404,
  VEHICLE_NOT_FOUND: 404,
  INVALID_STATUS_TRANSITION: 422,
  NO_VEHICLE_ASSIGNED: 422,
  VEHICLE_REQUIRED_FOR_STATUS: 422,
  VEHICLE_WRONG_OFFICE: 422,
  VEHICLE_WRONG_CATEGORY: 422,
  VEHICLE_ALREADY_BOOKED: 409,
};
